github: [VoidX3D]

patreon: voidx3d
open_collective: voidx3d
ko_fi: voidx3d
liberapay: voidx3d
issuehunt: voidx3d
polar: voidx3d
buy_me_a_coffee: voidx3d
thanks_dev: voidx3d

tidelift: npm/anime-tracker
community_bridge: anime-tracker
lfx_crowdfunding: anime-tracker

custom:
  - "https://voidx3d.netlify.app"
  - "https://github.com/VoidX3D"
